# JVM options per la daemon di Gradle
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# AndroidX obbligatorio per Compose
android.useAndroidX=true

# Ottimizzazioni
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
